# Generated by Django 4.1.5 on 2023-08-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
