# Generated by Django 4.1.5 on 2023-08-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
