# Generated by Django 4.1.5 on 2023-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=30)),
                ('Date_of_birth', models.DateTimeField()),
                ('Gender', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=80)),
                ('phone_no', models.CharField(max_length=25)),
                ('Medical_conditions', models.TextField()),
                ('Emergency_contact_no', models.CharField(max_length=25)),
            ],
        ),
    ]
