# Generated by Django 4.1.5 on 2023-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0005_remove_patientrecord_full_name_patientrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='Full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
