# Generated by Django 4.1.5 on 2023-08-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0006_remove_patientrecord_user_patientrecord_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
