# Generated by Django 4.1.5 on 2023-08-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0007_alter_patientrecord_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='Healthapp.customuser'),
            preserve_default=False,
        ),
    ]
