# Generated by Django 4.1.5 on 2023-08-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0008_patientrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='user',
        ),
    ]
