# Generated by Django 4.1.5 on 2023-08-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Healthapp', '0011_remove_patientrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_health_worker', to='Healthapp.customuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to='Healthapp.customuser')),
            ],
        ),
    ]
